api_endpoint: https://www.zohoapis.ca/books/v3
client_id: 1000.1AUQGRI6QABZXVWRF36S30OW9C9WVC
client_secret: 70ef0020bd9afc9715e980f85b630a9d4d56e2df37
data_center: CA
accounts_server: https://accounts.zohocloud.ca
organization_id: '110001648299'
refresh_token: 1000.c0898d8d628f95a28e36945e791759e9.66bfd205700238e8a89c20f8614cf8db
